version: "3"

services:
    php:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - .:/var/www/cron:cached

volumes:
    mysqldata:
        driver: local
